#!/bin/bash
# Run a command with the session-bound variables removed, so the tester is its own session.
exec env -u SESSION_INGRESS_URL -u CLAUDE_SESSION_INGRESS_TOKEN_FILE -u CLAUDE_CODE_POST_FOR_SESSION_INGRESS_V2 \
  -u CLAUDE_CODE_REMOTE -u CLAUDE_CODE_REMOTE_SESSION_ID -u CLAUDE_CODE_SESSION_ID -u CLAUDE_CODE_CHILD_SESSION \
  -u CLAUDE_CODE_SYNC_SESSION_REFS -u CLAUDE_CODE_REMOTE_SEND_KEEPALIVES -u CLAUDE_CODE_MESSAGING_SOCKET \
  -u CLAUDE_CODE_MESSAGING_TOKEN -u CLAUDE_CODE_TEE_SDK_STDOUT -u CLAUDE_CODE_SESSION_ATTENDED -u CCR_SESSION_PROFILE \
  -u CLAUDE_PID -u CLAUDECODE -u CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD -u CLAUDE_ADDITIONAL_DIRECTORIES \
  -u CLAUDE_CODE_DIAGNOSTICS_FILE -u GH_TOKEN -u GITHUB_TOKEN -u CLAUDE_CODE_ARTIFACT_ASSETS -u CLAUDE_CODE_ARTIFACT_DB \
  -u CLAUDE_CODE_ARTIFACT_MULTI_FILE -u CLAUDE_CODE_ARTIFACT_TYPES -u CLAUDE_CODE_ARTIFACT_TYPE_CATALOG \
  -u CLAUDE_CODE_ARTIFACT_TYPE_CLOUD_CREATE -u CLAUDE_CODE_SYNC_SKILLS -u TRACEPARENT "$@"
